config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  resources :posts do
    resources :comments, only: :create
  end
  resources :users, only: :show
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts;
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/posts/#{comment.post.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :move_to_index, except: [:index, :show]

  def index
    @post = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    if Post.create(post_params)
      redirect_to root_path
     else
       render :new
     end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  private
  def post_params
    params.require(:post).permit(:name, :image, :text).merge(user_id: current_user.id)
  end

  def move_to_index
    unless user_signed_in?
      redirect_to root_path
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @posts = user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictalk</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header class="header">
    <h1 class="insta"><a href="/">Home</a></h1>
    <% if user_signed_in? %>
      <%= link_to "マイページ", "/users/#{current_user.id}" %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      <%= link_to "投稿する", new_post_path %>
    <% else %>
      <%= link_to "ログイン", new_user_session_path %>
      <%= link_to "新規登録", new_user_registration_path %>
      <%= link_to "投稿する", new_post_path %>

    <% end %>
  </header>
  
  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="post">
  <% @post.each do |post| %>

    <div class="one_post">
      <div class="post_header">
        <div class="post_header_left">
          <div class="post_name">
            <%= link_to post.user.nickname, "/users/#{post.user.id}" %>
          </div>
        </div>
        <div class="post_header_right">
        
              <button class="accordion__title js-accordion-title">Menu</button>
              <div class="accordion__content">
                <%= link_to '詳細', post_path(post.id), method: :get %>
                <% if user_signed_in? && current_user.id == post.user_id %>
                  <%= link_to '削除', post_path(post.id), method: :delete %>
                <% end %>
          </div>
        </div>




      </div>
    
      <div class="post_text">
        <p><%= post.text %></p>
      </div>
      <%= image_tag post.image.variant(resize:'500x500') if post.image.attached? %>

    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="post">
  <h3>投稿する</h3>
  <%= form_with(model: @post, local: true) do |form| %>
    <%= form.text_area :text, placeholder: "text", rows: "10" %>
    <%= form.file_field :image %>
    <button type="submit" class="btn btn-primary">送信</button>
  <% end %>
    <%=link_to 'もどる', root_path, class:"btn btn-primary return" %>
</div>

app/views/posts/show.html.erb
<div class="show">

  <div class="show_left">
    <%= image_tag @post.image.variant(resize:'550x550') if @post.image.attached?  %>
  </div>

  <div class="show_right">
    <div class="poster">
      <%= @post.user.nickname %>
    </div>

    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>

    <div class="comment">
    <% if current_user %>
      <div class="message">
        <%= form_with(model: [@post, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
      </div>
      <div class="send">
        <%= form.submit "送信" %>
      </div>
      <% end %>
    <% else %>
      <p>※コメントには新規登録/ログインが必要です※</p>
    <% end %>
    </div>
  </div>

</div>

app/views/users/show.html.erb
<div class="post">
  <p><%= @nickname %>さんの投稿一覧</p>
  <% @posts.each do |post| %>
      <div class="one_post">
      <div class="post_header">
        <div class="post_header_left">
        </div>
        <div class="post_header_right">
          <%= link_to '詳細', post_path(post.id), method: :get %>
          <% if user_signed_in? && current_user.id == post.user_id %>
          <%= link_to '削除', post_path(post.id), method: :delete %>
          <% end %>
        </div>


      </div>
        <div class="post_text">
          <p><%= post.text %></p>
        </div>
        <%= image_tag post.image.variant(resize:'500x500') if post.image.attached? %>
      </div>
  <% end %>
</div>